# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog
email: jasonsduffy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will explore various aspects of software creation
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "http://darthstrom.com" # the base hostname & protocol for your site
twitter_username: DarthStrom
github_username:  DarthStrom

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
